---
refresh_interval: 2 # seconds
urls:
  - https://www.coolblue.nl/en/product/865866/playstation-5.html
  - https://www.mediamarkt.nl/nl/product/_sony-playstation-5-disk-edition-1664768.html
  - https://www.bol.com/nl/p/sony-playstation-5-console/9300000004162282/
  - https://www.gamemania.nl/Consoles/playstation-5/144093_playstation-5-disc-edition
...
